package com.vibhor.ecommerceanalytics.Security;

import com.vibhor.ecommerceanalytics.Exception.AiSecurityException;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Enterprise AI Guardrail:
 * Validates and sanitizes dynamic SQL queries generated by LLMs before execution.
 * Enforces strict Read-Only constraints (SELECT/WITH only) and blocks DDL/DML/Injection vectors.
 */
@Component
public class SqlGuardrailValidator {

    private static final List<String> FORBIDDEN_KEYWORDS = Arrays.asList(
            "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE",
            "RENAME", "GRANT", "REVOKE", "EXEC", "EXECUTE", "CALL",
            "CREATE", "REPLACE", "SHUTDOWN", "KILL", "LOCK", "UNLOCK",
            "FLUSH", "SET", "USE", "INTO OUTFILE", "INTO DUMPFILE",
            "INFORMATION_SCHEMA", "MYSQL.", "SYS.", "PERFORMANCE_SCHEMA"
    );

    private static final Pattern MULTI_STATEMENT_PATTERN = Pattern.compile(";\\s*\\S+");
    private static final Pattern COMMENT_PATTERN = Pattern.compile("(--|/\\*|\\*/|#)");

    public String validateAndSanitize(String rawSql) {
        if (rawSql == null || rawSql.trim().isEmpty()) {
            throw new AiSecurityException("LLM generated an empty SQL query.");
        }

        String cleanedSql = cleanMarkdownFormatting(rawSql).trim();
        String upperSql = cleanedSql.toUpperCase();

        if (!upperSql.startsWith("SELECT") && !upperSql.startsWith("WITH")) {
            throw new AiSecurityException("Security Violation: Only SELECT or CTE (WITH) queries are permitted.");
        }

        if (COMMENT_PATTERN.matcher(cleanedSql).find()) {
            throw new AiSecurityException("Security Violation: SQL comments are strictly prohibited in AI queries.");
        }

        if (MULTI_STATEMENT_PATTERN.matcher(cleanedSql).find()) {
            throw new AiSecurityException("Security Violation: Multiple SQL statements detected in a single query.");
        }

        for (String forbidden : FORBIDDEN_KEYWORDS) {
            Pattern keywordPattern = Pattern.compile("\\b" + Pattern.quote(forbidden) + "\\b", Pattern.CASE_INSENSITIVE);
            if (keywordPattern.matcher(upperSql).find()) {
                throw new AiSecurityException("Security Violation: Forbidden SQL keyword detected: " + forbidden);
            }
        }

        if (cleanedSql.endsWith(";")) {
            cleanedSql = cleanedSql.substring(0, cleanedSql.length() - 1).trim();
        }

        return cleanedSql;
    }

    private String cleanMarkdownFormatting(String sql) {
        return sql.replaceAll("(?i)```sql", "")
                  .replaceAll("```", "")
                  .trim();
    }
}
