spring.application.name=ecommerce-analytics
spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce

spring.datasource.username=root

spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# ==============================
# NVIDIA NIM + Spring AI
# ==============================

spring.ai.model.chat=openai

spring.ai.openai.api-key=${NVIDIA_API_KEY}
spring.ai.openai.base-url=https://integrate.api.nvidia.com/v1

# Explicitly configure the ChatModel connection
spring.ai.openai.chat.api-key=${NVIDIA_API_KEY}
spring.ai.openai.chat.base-url=https://integrate.api.nvidia.com/v1

spring.ai.openai.chat.model=meta/llama-3.1-70b-instruct

# NVIDIA requires this explicitly
spring.ai.openai.chat.max-tokens=2048

# NVIDIA chat API doesn't provide embeddings
spring.ai.model.embedding=none